spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**
                
            - id: activity-service
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path=/activity/**
                
            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/recommendation/**
                

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/